version: '3'
services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    hostname: frontend
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
        
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    hostname: backend
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
  
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    image: db
    hostname: db
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /data/db:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    