version: '3'
services:
  db:
    image: mongo
    hostname: db
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - 27017:27017
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: rootuser
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
        MONGO_INITDB_DATABASE: teamtodo
        MONGO_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init-mongo.js
    volumes:
      - /data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    